//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A8_Berrios_Sean.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/map", ReplyAction="http://tempuri.org/IService1/mapResponse")]
        System.Collections.Generic.Dictionary<string, int> map(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/map", ReplyAction="http://tempuri.org/IService1/mapResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> mapAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/reduce", ReplyAction="http://tempuri.org/IService1/reduceResponse")]
        System.Collections.Generic.Dictionary<string, int> reduce(System.Collections.Generic.Dictionary<string, int> input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/reduce", ReplyAction="http://tempuri.org/IService1/reduceResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> reduceAsync(System.Collections.Generic.Dictionary<string, int> input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/combine", ReplyAction="http://tempuri.org/IService1/combineResponse")]
        string combine(System.Collections.Generic.Dictionary<string, int> input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/combine", ReplyAction="http://tempuri.org/IService1/combineResponse")]
        System.Threading.Tasks.Task<string> combineAsync(System.Collections.Generic.Dictionary<string, int> input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : A8_Berrios_Sean.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<A8_Berrios_Sean.ServiceReference1.IService1>, A8_Berrios_Sean.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, int> map(string input) {
            return base.Channel.map(input);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> mapAsync(string input) {
            return base.Channel.mapAsync(input);
        }
        
        public System.Collections.Generic.Dictionary<string, int> reduce(System.Collections.Generic.Dictionary<string, int> input) {
            return base.Channel.reduce(input);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> reduceAsync(System.Collections.Generic.Dictionary<string, int> input) {
            return base.Channel.reduceAsync(input);
        }
        
        public string combine(System.Collections.Generic.Dictionary<string, int> input) {
            return base.Channel.combine(input);
        }
        
        public System.Threading.Tasks.Task<string> combineAsync(System.Collections.Generic.Dictionary<string, int> input) {
            return base.Channel.combineAsync(input);
        }
    }
}
