//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="myInterface")]
public interface myInterface
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/myInterface/PiValue", ReplyAction="http://tempuri.org/myInterface/PiValueResponse")]
    double PiValue();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/myInterface/PiValue", ReplyAction="http://tempuri.org/myInterface/PiValueResponse")]
    System.Threading.Tasks.Task<double> PiValueAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/myInterface/absValue", ReplyAction="http://tempuri.org/myInterface/absValueResponse")]
    int absValue(int intVal);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/myInterface/absValue", ReplyAction="http://tempuri.org/myInterface/absValueResponse")]
    System.Threading.Tasks.Task<int> absValueAsync(int intVal);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface myInterfaceChannel : myInterface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class myInterfaceClient : System.ServiceModel.ClientBase<myInterface>, myInterface
{
    
    public myInterfaceClient()
    {
    }
    
    public myInterfaceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public myInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public myInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public myInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public double PiValue()
    {
        return base.Channel.PiValue();
    }
    
    public System.Threading.Tasks.Task<double> PiValueAsync()
    {
        return base.Channel.PiValueAsync();
    }
    
    public int absValue(int intVal)
    {
        return base.Channel.absValue(intVal);
    }
    
    public System.Threading.Tasks.Task<int> absValueAsync(int intVal)
    {
        return base.Channel.absValueAsync(intVal);
    }
}
